### ISSUE TITLE
Errror message: Failed to initialize libovr

### ISSUE THREAD

**Issue by Friese611** [LukeRoss00/nolf2-real-mod#1]
Hi, i get this error message "Failed to initialize libovr" if i try to start the game. Any ideas?
i5 6600k, 16gb ddr4, Gtx 980ti, Win 10, HTC Vive

**Comment by LukeRoss00** [comment]
Hi!
Thanks for helping me debug this issue.

Could you please unzip [this](https://github.com/LukeRoss00/nolf2-real-mod/files/1691112/Debug.zip) file into your mod installation folder and try again? It should give you a more detailed error message: can you copy what it says with Ctrl+C and paste it here please?

Also, does SteamVR start when you launch Lithtech.exe? If it starts, does it give any error messages?

**Comment by Friese611** [comment]
---------------------------
Hi,
SteamVR doesn´t start. This is the error message with the new file:

---------------------------
No One Lives Forever 2 VR
---------------------------
Failed to initialize libOVR (error -3003)
OpenVR loaded: yes
Revive loaded: yes
Last error: -1004, ""
---------------------------
OK   
---------------------------

**Comment by Friese611** [comment]
For your information: I have also the Oculus Software installed but not active running (i can start it with a script file if i need the Oculus Store to play the games there). If i have the Oculus software running i get this error with the new file: 
---------------------------
No One Lives Forever 2 VR
---------------------------
Oculus Rift not detected (error -1007)
---------------------------
OK   
---------------------------
That sounds normal to me because i don´t own the Rift. I have also the latest REVIVE Software installed.

**Comment by LukeRoss00** [comment]
That last bit of information you added might be important, because error -3003 is precisely "Couldn't connect to the OVR Service."

Could you please try two additional things:
1. Start the Oculus service, then launch Lithtech.exe (send me the new error message if it changes in any way);
2. If 1. doesn't work, start the Oculus service, then start SteamVR manually, and finally launch Lithtech.exe (again it would be helpful to see the new error message if different)

**Comment by LukeRoss00** [comment]
There are actually two important components to the Oculus software: the client (i.e., Oculus Home) which should not be needed for NOLF2 to work, and the server ("Oculus VR Runtime Service") which runs in the background. When you say that you have the Oculus software running, do you mean the Oculus Home or the background service?

**Comment by Friese611** [comment]
The error message is the same in both ways:

---------------------------
No One Lives Forever 2 VR
---------------------------
Oculus Rift not detected (error -1007)
---------------------------
OK   
---------------------------
 If i start only steamvr manually (without the oculus service running) i see the same "Failed to initializelibOVR... " error.

**Comment by Friese611** [comment]
I use this script for the Oculus runtime: 
sc config OVRService start= demand
net start "OVRService"
if %errorlevel% == 2 net stop "OVRService"

If i only start the script and don´t have the client open than the client starts automaticly if i use the Lithtech.exe. 
Sorry for my english ;-)

**Comment by Friese611** [comment]
If i close the Oculus runtime with the script file i can´t see any Oculus software running in the task manager.

**Comment by LukeRoss00** [comment]
Okay. This is super weird, because the game reports OpenVR and Revive as being loaded, but the error messages and the behavior you described are those that would be expected when Revive is not active.

Are you using an antivirus that might be blocking the .dll's from being executed? Windows Defender is good, but other third-party antivirus programs tend to be a little over-aggressive at times.

**Comment by Friese611** [comment]
i have the Windows defender and Malwarebytes Anti Exploit running. But i tried it before without running Malwarebytes and got the same error. I read in a reddit post that another user has the same problem.

**Comment by LukeRoss00** [comment]
Yes, thanks for all the info!

I also have reports of people successfully running the mod with the Vive (and without a Rift of course), so I'm trying to isolate what the difference among the systems may be that makes it fail on some configurations and work on others.

**Comment by Friese611** [comment]
Anyway...thank you very much for your mod and have a nice day.

**Comment by LukeRoss00** [comment]
Could you try injecting the program with your installed version of Revive instead of using the embedded one? That is, run SteamVR, open Revive's system tray menu, select "Inject...", and point it to the Lithtech.exe executable.

**Comment by Friese611** [comment]
Lol...that works ;-)

**Comment by LukeRoss00** [comment]
Haha, that's bizarre. I created the embedded version of Revive because other users were having the opposite problem, where Inject wasn't working.

Thank you so much for your time, and I'm glad that it works for you in the end. If by any chance you manage to find out what was wrong with the embedded version on your system, please post here so it might help other users!

**Comment by Friese611** [comment]
Ok...i thank you!
