### ISSUE TITLE
Aiming is too high while crouching (sitting at PC)

### ISSUE THREAD

**Issue by bardokhofmeier896** [LukeRoss00/nolf2-real-mod#6]
Hi LukeRoss00,
first of all a big thank you for this mod. I'm a little ashamed that that i only now discovered it, because it brings this game to an even higher level and ist brilliantly done.

But i do have one issue. Cate constantly aimes to high, if i don't stand physically. 
I read it should be fixed, but i still have that problem. And i don't want to play standing with a controller, this is nolf after all :)

I downloaded that game vom Revive, deleted the widescreen patch and the "Game" folder, but sadly it still persists. Also i use a german patch from schote.
I used the mod version from github:
https://github.com/LukeRoss00/nolf2-real-mod/releases/tag/r3/NOLF2_REAL_mod_by_LukeRoss_r3_DE.rar

I'm really hoping for your wisdom, because my neck is killing me after an hour of gameplay.

Thanks in advance
bardokhofmeier896

**Comment by LukeRoss00** [comment]
Hi, sorry that I'm only seeing this now! I wasn't expecting anybody to post here any longer :-)

Crouching and sitting are two different things: I assume that what you mean is playing seated. Which system do you use (Oculus Rift S, Valve Index, ...)? Also, what is the German patch from schote that you mentioned?

**Comment by bardokhofmeier896** [comment]
Hi, no problem i'm glad you still answer :-)
I still play this game ones every 2 Years, but i only got the headset. I didn't even expect there to be vr support, was just looking for quality of life mods.
Yeah i mean playing seated  and I got myself a Rift S.
The german patch ist a language patch for the german language (texts and dialogoues), nothing more, just thought i should at least mention it. It's my native language and i just like the german voice more. 
Kate sounds to credible/serious in english ;-)

**Comment by LukeRoss00** [comment]
OK, you can try a few things:
1. make sure that you are already seated when you launch the game
2. make sure that you are not using Revive and that SteamVR is not started (the mod uses the Oculus runtime natively)
3. use `Lithtech.exe` to start the game directly and not the NOLF2 launcher
4. extract the mod file `NOLF2_REAL_mod_by_LukeRoss_r3_DE.rar` again and let it overwrite all files (your game options will be reset to defaults but your saves won't be affected)
5. delete everything in the `Custom\Mods` folder

Let me know if that works for you, otherwise we'll try something else!

**Comment by bardokhofmeier896** [comment]
Okay sadly that didn't work.
I uninstalled SteamVR, just to be sure, my mods folder is empty and I’ve overwritten the mod files again. No matter if I start
I'm not sure how to use or not use revive. I deleted the ReviveNolf folder but that does no good.

I always start the game via the Lithtech.exe. Also taking out the German patch doesn't change anything (well apart from the language :)

But I did notice that my aim is to high, even if I stand. I was sure that was good when i tried before, but it now is that way even with a another newly installed instance...
So apparently the aim is always a bit too high.

**Comment by LukeRoss00** [comment]
That's weird. I cannot reproduce the issue here: I've tried both seated and standing and aiming has no misalignment for me. You know NOLF2 well, so I assume that you wait until the crosshair shows maximum precision before shooting?

Let's see if your game installation has become corrupted somehow: open a command prompt, go to your NOLF2 folder, then type the command `dir /s > out.txt` and attach the resulting `out.txt` file here.

**Comment by bardokhofmeier896** [comment]
[out.txt](https://github.com/LukeRoss00/nolf2-real-mod/files/4611548/out.txt)

Okey maybe i phrased that wrong. The crosshair itself is too high. While i look straight the crosshair ist at the top of the wall before me.

**Comment by LukeRoss00** [comment]
Looking at the directory I see two things of interest: your `VRlaunchcmds.txt` has a nonstandard size, as if it's been edited, and your profile is called "Spieler" instead of "Player".

Could you attach here your `VRlaunchcmds.txt` file? Also, try restoring your `autoexec.cfg` from the mod .rar archive and starting a new game as Player.

**Comment by bardokhofmeier** [comment]
My VRlauchcmds.txt was added a line to include the german patch, an that also changed my savegame folder the german, hence Spieler instead of Player.

[out.txt](https://github.com/LukeRoss00/nolf2-real-mod/files/4621210/out.txt)
I made a clean install without the german patch and let the command run again.
If I find out how to make a screenshot that i will make one to see if you even consider my crosshair to high, or if it works as intended :)

**Comment by bardokhofmeier** [comment]
![OculusScreenshot1589365694](https://user-images.githubusercontent.com/52507738/81801998-91ba9f00-9515-11ea-99ed-6d9aa3933efd.jpeg)
The screenshot.

**Comment by LukeRoss00** [comment]
So, what's the problem? Looks perfectly normal to me. I've managed to capture a screenshot from SweViver's [video](https://www.youtube.com/watch?v=hJhE84R74_0) from 2018 that is almost in the same position and shows the same height relationship between the crosshair and the crossbow.

![image](https://user-images.githubusercontent.com/34809409/81805907-00026000-951c-11ea-9db6-a949ec92ee8c.png)

The crosshair is aligned to your gaze, as you can also see from this other screenshot that I took from the Oculus Mirror (the crosshair lies at the vertical center of the image):

![image](https://user-images.githubusercontent.com/34809409/81806186-6a1b0500-951c-11ea-836a-543d8a21d1fb.png)

**Comment by bardokhofmeier** [comment]
On actually looking at it I admit that my screenshot wasn't good. I made one where the problem is actually visible.
Yeah the crosshair is exactly in the middle of the screen, that is always true. But I think I didn't give a good explanation of my problem, sorry for that.

![OculusScreenshot1589376784](https://user-images.githubusercontent.com/52507738/81819295-6b096200-952f-11ea-8036-615f72c731c6.jpeg)
This is the default height of sight. If I hold my head looking straight forward, my aim is at the ceiling. So i have to constantly look down. Picking item that are placed on the ground is a task itself :)
To aim at a height like in your second screenshot, i would have to look down at my keyboard.

**Comment by ajantaju** [comment]
Are you using https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings ? Or any other things that might offset the crosshair?

**Comment by bardokhofmeier** [comment]
Hi, sorry i didn't response anymore, my headset broke. I now have to get it replaced, which could take a while because i didn't buy it from oculus directly. Sorry again for forgetting to write.

Would love to get back at this once the new headset is here :)
